# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main_pyside.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'cv2',
        'numpy',
        'scipy.optimize',
        'imagehash',
        'fitz',
        'pptx',
        'comtypes.client',
        'core',
        'core.document',
        'core.page_matcher',
        'core.image_comparator',
        'core.exclusion_zone',
        'core.session',
        'utils',
        'utils.image_utils',
        'gui_pyside',
        'gui_pyside.main_window',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'wx',
        'wxPython',
        'PyQt5',
        'PyQt6',
        'torch',
        'pandas',
        'matplotlib',
        'IPython',
        'jupyter',
        'notebook',
        'tkinter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PPTPDFComparator_PySide',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
